api = "0.10"

[buildpack]
id = "com.stackly.tools"
version = "0.0.1"
name = "Stackly Tools Buildpack"

[[stacks]]
id = "heroku-22"

[metadata]
description = "Installs security analysis tools (semgrep, trivy, enry)"

[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "linux"
arch = "arm64"
